### ISSUE TITLE
【Help!!!!!】Get paper pdf

### ISSUE THREAD

**Issue by freeclouds** [SS47816/fiss_planner#1]
hi ,I'm sorry to bother you，
I can't find the address to download the paper from the Internet，
Can you send a paper to my email?
paper: FISS: A Trajectory Planning Framework Using Fast Iterative Search and Sampling Strategy for Autonomous Driving，
email: 1277042767@qq.com
Thanks a lot!

**Comment by SS47816** [comment]
Hi there, 

Thank you for your interest in our work!

Our paper is accessible on IEEE Xplore: https://doi.org/10.1109/LRA.2022.3191940
You may log in and download the paper from there. 😃 

Regards,
Shuo
