### ISSUE TITLE
[helper]can't run code。

### ISSUE THREAD

**Issue by Jonyian** [SS47816/fiss_planner#2]
Hello, I have this problem in the last step when I run the code on your github. need your help, thank you very much：

roslaunch fiss_planner fiss_planner.launch
RLException: [fiss_planner.launch] is neither a launch file in package [fiss_planner] nor is [fiss_planner] a launch file name
The traceback for the exception was written to the log file

**Comment by SS47816** [comment]
Hi,

From what you described,  ROS did not find this package named `fiss_planner` in the paths.

I suspect it is because after building the package, you forgot to `source`:
```bash
# source 
source devel/setup.bash
```

Please try the above fix and see if you can get it to work.

Regards,
Shuo

**Comment by Jonyian** [comment]
Hello, I have run the steps you mentioned. the version I use is Ubuntu18.04+ros1. When I run "catkin_make", I get an error and choose "catkin build". Very disturbing! Thanks again for your reply


`jon@jon:~/fiss_planner$ catkin build 
-----------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/melodic
Workspace:                   /home/jon/fiss_planner
-----------------------------------------------------------
Build Space:        [exists] /home/jon/fiss_planner/build
Devel Space:        [exists] /home/jon/fiss_planner/devel
Install Space:      [unused] /home/jon/fiss_planner/install
Log Space:          [exists] /home/jon/fiss_planner/logs
Source Space:       [exists] /home/jon/fiss_planner/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] No packages were found in the source space '/home/jon/fiss_planner/src'
[build] No packages to be built.
[build] Package table is up to date.                                          
[build] Summary: All 0 packages succeeded!                                    
[build]   Ignored:   None.                                                    
[build]   Warnings:  None.                                                    
[build]   Abandoned: None.                                                    
[build]   Failed:    None.                                                    
[build] Runtime: 0.0 seconds total.                                           
jon@jon:~/fiss_planner$ source devel/setup.bash
jon@jon:~/fiss_planner$ roslaunch fiss_planner fiss_planner.launch
RLException: [fiss_planner.launch] is neither a launch file in package [fiss_planner] nor is [fiss_planner] a launch file name
The traceback for the exception was written to the log file
`

**Comment by SS47816** [comment]
Hi,

I realized your path to the repo is: `~/fiss_planner/`

Instead, this ROS pkg should be used within a catkin workspace, something like this: `~/catkin_ws/src/fiss_planner/`

Sorry that the original installation instructions might be misleading. I have updated that section and you can follow the steps in the latest version now. 

Regards,
Shuo
