### ISSUE TITLE
i can not run the node

### ISSUE THREAD

**Issue by tqlblzj** [SS47816/fiss_planner#3]
I can see the rqt_reconfigure_param GUI, but there are some wrong messages when i launch, should i install lgsvl and mission first?

ERROR: cannot launch node of type [mission_planner/mission_planner]: mission_planner
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/lzj/ros_ws/src
ROS path [2]=/home/lzj/catkin_ws/src
ROS path [3]=/opt/ros/melodic/share
process[fiss_planner_node-3]: started with pid [1388]
ERROR: cannot launch node of type [lgsvl_utils/detected_objects_visualizer]: lgsvl_utils
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/lzj/ros_ws/src
ROS path [2]=/home/lzj/catkin_ws/src
ROS path [3]=/opt/ros/melodic/share
process[rqt_reconfigure-5]: started with pid [1389]

**Comment by fuyueagain** [comment]
hi , i have meeted the same problem...

**Comment by fuyueagain** [comment]
> I can see the rqt_reconfigure_param GUI, but there are some wrong messages when i launch, should i install lgsvl and mission first?
> 
> ERROR: cannot launch node of type [mission_planner/mission_planner]: mission_planner ROS path [0]=/opt/ros/melodic/share/ros ROS path [1]=/home/lzj/ros_ws/src ROS path [2]=/home/lzj/catkin_ws/src ROS path [3]=/opt/ros/melodic/share process[fiss_planner_node-3]: started with pid [1388] ERROR: cannot launch node of type [lgsvl_utils/detected_objects_visualizer]: lgsvl_utils ROS path [0]=/opt/ros/melodic/share/ros ROS path [1]=/home/lzj/ros_ws/src ROS path [2]=/home/lzj/catkin_ws/src ROS path [3]=/opt/ros/melodic/share process[rqt_reconfigure-5]: started with pid [1389]

hi , i have meeted the same problem...

**Comment by fuyueagain** [comment]
Another error....

```
[ERROR] [1665060972.663747124]: Skipped loading plugin with error: XML Document '/opt/ros/melodic/share/rqt_virtual_joy/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/melodic/share/rqt_virtual_joy/plugin.xml" in package "rqt_virtual_joy" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/melodic/share/rqt_virtual_joy/plugin.xml" in package "rqt_virtual_joy" not found

```

**Comment by Highlight123** [comment]
**I have meeted the same problem, how to solve the problem???**
ERROR: cannot launch node of type [mission_planner/mission_planner]: mission_planner
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/highlight/Documents/catkin_fiss/src
ROS path [2]=/opt/ros/melodic/share
process[fiss_planner_node-3]: started with pid [12275]
ERROR: cannot launch node of type [lgsvl_utils/detected_objects_visualizer]: lgsvl_utils
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/highlight/Documents/catkin_fiss/src
ROS path [2]=/opt/ros/melodic/share
ERROR: cannot launch node of type [rqt_reconfigure/rqt_reconfigure]: rqt_reconfigure
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/highlight/Documents/catkin_fiss/src
ROS path [2]=/opt/ros/melodic/share

**Comment by SS47816** [comment]
Hi,

This issue was due to the fact that the launch file was looking for several AutowareAI packages that `lgsvl_utils` previously did not include. Now I have included the minimal Autoware packages (with minor modifications) required to run this planner in the `lgsvl_utils` repo. 

You may now refer to the latest version of installation and usage [instructions](https://github.com/SS47816/fiss_planner#installation) in the repo. Do let me know if you encountered any other issues!


Best regards,
Shuo

**Comment by tqlblzj** [comment]
> Hi,
> 
> This issue was due to the fact that the launch file was looking for several AutowareAI packages that `lgsvl_utils` previously did not include. Now I have included the minimal Autoware packages (with minor modifications) required to run this planner in the `lgsvl_utils` repo.
> 
> You may now refer to the latest version of installation and usage [instructions](https://github.com/SS47816/fiss_planner#installation) in the repo. Do let me know if you encountered any other issues!
> 
> Best regards, Shuo

I get it, thank you!
