### ISSUE TITLE
[helper]:  Code understanding

### ISSUE THREAD

**Issue by Highlight123** [SS47816/fiss_planner#4]
Dear Dr.Sun, 
    I have some code understanding problems. Very disturbing! Thank you very much!
    Is global frame equal to map frame?  Is candidate_trajs_ generated in frenet frame? checkCollisions is in global frame?
    The control outputs is calculated in map frame?

**Comment by SS47816** [comment]
Hi,

Yes, the global frame is referring to the Map frame (in Cartesian); the subsequent collision checking, and control are all done in this frame.

Yes, `candidate_trajs_ generated` is in the Frenet frame.

Sorry for the late reply! 

Best regards, 
Shuo
