### ISSUE TITLE
error in obstacle prediction trajectory

### ISSUE THREAD

**Issue by tmacattank** [SS47816/fiss_planner#5]
https://github.com/SS47816/fiss_planner/blob/a930e22ba331bd1aa1b5f16f8c5e287b5f465abd/include/fiss_planner/fiss_planner.cc#L705 
in this line, obstacle prediction info in y axis is wrongly emplaced back with x axis info. It makes collision-check no sense.

**Comment by SS47816** [comment]
Hi,

Thank you for spotting the error! It was indeed a typo!

This was an earlier version of our code and we fixed this problem (and a number of other issues we spotted elsewhere) in a later version. As right now we are in the middle of busy building a new code base for this (together with some other projects), we might not be able to maintain this repo for a period of time. Hope you can understand that! 

The new code base with some major updates will be released later. (Hopefully soon!)

**Comment by LangDaoAI** [comment]
@SS47816 great work!  and when the new code base will be released?
